- hosts: localhost
  tasks:
    # install gcloud cli
    - name: Install packages for gcloud CLI
      become: true
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - gnupg
    - name: Add gcloud GPG
      become: true
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
    - name: Add gcloud repo
      become: true
      apt_repository:
        repo: deb https://packages.cloud.google.com/apt cloud-sdk main
        state: present
    - name: Update apt
      become: true
      apt:
        update_cache: yes
    - name: Install gcloud cli
      become: true
      apt:
        name:
          - google-cloud-cli
          - google-cloud-cli-cloud-run-proxy
          - google-cloud-sdk-gke-gcloud-auth-plugin
          - kubectl
