- hosts: localhost
  tasks:
    # basic packages
    - name: Install basic packages
      become: true
      package:
        name: [g++, cmake, golang-go, emacs]

    # install npm
    - name: Add nodejs GPG
      become: true
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present
    - name: Add nodejs repo
      become: true
      apt_repository:
        repo: deb https://deb.nodesource.com/node_18.x jammy main
        state: present
    - name: Update apt
      become: true
      apt:
        update_cache: yes
    - name: Install nodejs
      become: true
      apt:
        name:
          - nodejs

    # setup zsh
    - name: Install zsh
      become: true
      package:
        name: zsh
    - name: Change user shell to zsh
      become: true
      user:
        name: "{{ ansible_user_id }}"
        shell: zsh
    - name: Register zprofile
      blockinfile:
        create: true
        path: ~/.zprofile
        block: |
          . {{ (ansible_env.PWD, "zprofile") | path_join }}
    - name: Register zshrc
      blockinfile:
        create: true
        path: ~/.zshrc
        block: |
          . {{ (ansible_env.PWD, "zshrc") | path_join }}


    # git configs
    - git_config:
        name: user.name
        scope: global
        value: Kohei Morita
    - git_config:
        name: user.email
        scope: global
        value: yosupo06@gmail.com
    - git_config:
        name: alias.st
        scope: global
        value: status
    - git_config:
        name: alias.cob
        scope: global
        value: checkout -b
    - git_config:
        name: alias.view
        scope: global
        value: log --oneline --decorate --graph --branches --tags
    - git_config:
        name: credential.helper
        scope: global
        value: store
    - git_config:
        name: core.excludesFile
        scope: global
        value: |-
          {{ (ansible_env.PWD, "gitignore_global") | path_join }}
          

    # install docker
    - name: Install packages for Docker
      become: true
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
    - name: Add docker GPG
      become: true
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add docker repo
      become: true
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
        state: present
    - name: Update apt
      become: true
      apt:
        update_cache: yes
    - name: Install docker
      become: true
      apt:
        name: docker-ce
    - name: Add user to docker group
      become: true
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: true
    - name: Restard docker
      become: true
      service:
        name: docker
        state: restarted

    # install gcloud cli
    - name: Install packages for gcloud CLI
      become: true
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - gnupg
    - name: Add gcloud GPG
      become: true
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
    - name: Add gcloud repo
      become: true
      apt_repository:
        repo: deb https://packages.cloud.google.com/apt cloud-sdk main
        state: present
    - name: Update apt
      become: true
      apt:
        update_cache: yes
    - name: Install gcloud cli
      become: true
      apt:
        name:
          - google-cloud-cli
          - google-cloud-cli-cloud-run-proxy
