- hosts: localhost
  tasks:
    - name: Install zsh
      become: true
      package:
        name: zsh
    - name: Change user shell to zsh
      become: true
      user:
        name: "{{ ansible_user_id }}"
        shell: zsh

    - name: Register zprofile
      blockinfile:
        create: true
        path: ~/.zprofile
        block: |
          . {{ (ansible_env.PWD, "zprofile") | path_join }}
    - name: Register zshrc
      blockinfile:
        create: true
        path: ~/.zshrc
        block: |
          . {{ (ansible_env.PWD, "zshrc") | path_join }}

    # git configs
    - git_config:
        name: user.name
        scope: global
        value: Kohei Morita
    - git_config:
        name: user.email
        scope: global
        value: yosupo06@gmail.com
    - git_config:
        name: alias.st
        scope: global
        value: status
    - git_config:
        name: alias.cob
        scope: global
        value: checkout -b
    - git_config:
        name: alias.view
        scope: global
        value: log --oneline --decorate --graph --branches --tags
    - git_config:
        name: credential.helper
        scope: global
        value: store

    # install docker
    - name: Install packages for Docker
      become: true
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
    - name: Add docker GPG
      become: true
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add docker repo
      become: true
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
    - name: Update apt
      become: true
      apt:
        update_cache: yes
    - name: Install docker
      become: true
      apt:
        name: docker-ce
    - name: Add user to docker group
      become: true
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: true
    - name: Restard docker
      become: true
      service:
        name: docker
        state: restarted
