template_src = "/Users/koheim/personal/procon/library/Algorithm/src/base.cpp"
contest_template = [
    "/Users/koheim/personal/procon/contest/template/.vscode"
]
compile_debug = """
{{.CXX}} {{.Source}} -o {{.Output}}
-std=c++17 -g -DLOCAL -march=native
-Wall -Wextra -Wshadow -Wconversion -Wno-sign-conversion
-fsanitize=address,undefined -fno-omit-frame-pointer
-I ~/yosupo/procon/library/Algorithm/src
-I ~/yosupo/procon/library/ac-library
-I ~/yosupo/procon/library/yosupo-library
"""
compile_opt = """
{{.CXX}} {{.Source}} -o {{.Output}}
-std=c++17 -g -DLOCAL -O2 -march=native
-Wall -Wextra -Wshadow -Wconversion -Wno-sign-conversion
-I /Users/koheim/personal/procon/library/Algorithm/src
-I /Users/koheim/personal/procon/library/ac-library
-I /Users/koheim/personal/procon/library/yosupo-library
"""
bundle_source = """
/Users/koheim/personal/procon/library/yosupo-library/expander.py {{.Source}} -c
--lib /Users/koheim/personal/procon/library/Algorithm/src
--lib /Users/koheim/personal/procon/library/ac-library
--lib /Users/koheim/personal/procon/library/yosupo-library
> {{.Output}}
"""

pbcopy = "pbcopy"
