- hosts: localhost
  tasks:
    # alias
    - git_config:
        name: alias.st
        scope: global
        value: status
    - git_config:
        name: alias.cob
        scope: global
        value: checkout -b
    - git_config:
        name: alias.view
        scope: global
        value: log --oneline --decorate --graph --branches --tags
    # personal settings
    - name: Register gitconfig-yosupo
      blockinfile:
        create: true
        path: ~/.gitconfig
        marker: "# {mark} yosupo gitconfig block"
        block: |
          [includeIf "gitdir:~/yosupo/"]
            path = .gitconfig-yosupo
    - git_config:
        name: core.excludesFile
        scope: file
        file: ~/.gitconfig-yosupo
        value: |-
          {{ (ansible_env.PWD, "../../config/gitignore-global") | path_join }}
    - git_config:
        name: user.name
        scope: file
        file: ~/.gitconfig-yosupo
        value: Kohei Morita
    - git_config:
        name: user.email
        scope: file
        file: ~/.gitconfig-yosupo
        value: yosupo06@gmail.com
