- hosts: localhost
  tasks:
    - name: Register zprofile
      blockinfile:
        create: true
        marker: "# {mark} yosupo zprofile block"
        path: ~/.zprofile
        block: |
          . {{ (ansible_env.PWD, "../../config/zprofile") | path_join }}
    - name: Register zshrc
      blockinfile:
        create: true
        marker: "# {mark} yosupo zshrc block"
        path: ~/.zshrc
        block: |
          . {{ (ansible_env.PWD, "../../config/zshrc") | path_join }}
