- hosts: localhost
  tasks:
    - name: Add nodejs GPG
      become: true
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present
    - name: Add nodejs repo
      become: true
      apt_repository:
        repo: deb https://deb.nodesource.com/node_18.x jammy main
        state: present
    - name: Update apt
      become: true
      apt:
        update_cache: yes
    - name: Install nodejs
      become: true
      apt:
        name:
          - nodejs
